# -*- coding: utf-8 -*-
"""To_find_the_best_coefficients.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qeHF8v3dm18LddGOWC7ox7tLXyki2C6
"""

from google.colab import files
files.upload();

import pandas as pd
import numpy as np
from itertools import product
from sklearn.metrics import r2_score, mean_squared_error

# =====================================================
# Load your data
# =====================================================

df = pd.read_excel("M1_AR_Ferrite_.xlsx")

# =====================================================
# Normalize descriptors
# =====================================================

df["occ_norm"] = (
    df["Total_occurrences"] /
    df["Total_occurrences"].max()
)

df["sc100"] = (
    df["Spot_count_100"] /
    df["Spot_count_100"].max()
)

df["sc110"] = (
    df["Spot_count_110"] /
    df["Spot_count_110"].max()
)

df["sc111"] = (
    df["Spot_count_111"] /
    df["Spot_count_111"].max()
)

# Interaction terms

df["sc110_sc111"] = df["sc110"] * df["sc111"]
df["sc100_sc111"] = df["sc100"] * df["sc111"]

# Experimental target

y_exp = df["Experimental_Fraction"].values

# =====================================================
# Physics-guided coefficient search
# =====================================================

best_r2 = -999
best_rmse = 999
best_coeffs = None

# search ranges

occ_range = np.arange(0.10,0.16,0.01)

sc100_range = np.arange(0.19,0.25,0.01)

sc110_range = np.arange(0.20,0.30,0.01)

sc111_range = np.arange(0.35,0.45,0.01)

int110111_range = np.arange(0.25,0.35,0.01)

int100111_range = np.arange(0.19,0.25,0.01)

for w_occ in occ_range:

    for w100 in sc100_range:

        for w110 in sc110_range:

            for w111 in sc111_range:

                # enforce physical hierarchy
                if not (w111 > w110 > w100 > w_occ):
                    continue

                for w110111 in int110111_range:

                    for w100111 in int100111_range:

                        # interaction hierarchy
                        if w110111 <= w100111:
                            continue

                        y_pred = (
                            w_occ*df["occ_norm"]
                            + w100*df["sc100"]
                            + w110*df["sc110"]
                            + w111*df["sc111"]
                            + w110111*df["sc110_sc111"]
                            + w100111*df["sc100_sc111"]
                        )

                        r2 = r2_score(y_exp,y_pred)

                        rmse = np.sqrt(
                            mean_squared_error(
                                y_exp,
                                y_pred
                            )
                        )

                        if r2 > best_r2:

                            best_r2 = r2
                            best_rmse = rmse

                            best_coeffs = [
                                w_occ,
                                w100,
                                w110,
                                w111,
                                w110111,
                                w100111
                            ]

print("\nBest Coefficients")
print("-----------------------")
print(f"occ_norm      = {best_coeffs[0]:.2f}")
print(f"sc100         = {best_coeffs[1]:.2f}")
print(f"sc110         = {best_coeffs[2]:.2f}")
print(f"sc111         = {best_coeffs[3]:.2f}")
print(f"sc110*sc111   = {best_coeffs[4]:.2f}")
print(f"sc100*sc111   = {best_coeffs[5]:.2f}")
